### ISSUE TITLE
Chart Editor Bug

### ISSUE THREAD

**Issue by Miguelpescript** [mcagabe19/FNF-PsychEngine-Mobile#1]
### Describe your bug here.

When i try to access Chart Editor it says it have a invaliad directory, this happens in every song

### Command Prompt/Terminal logs (if existing)

```bash
Invalid directory
/opt/hostedtoolcache/haxe/4.2.5/x64/std/cpp/_std/sys/FileSystem.hx (line 101)
states/editors/ChartingState.hx (line 915)
states/editors/ChartingState.hx (line 356)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Karim-Akra** [comment]
Chart editor dosent work in beta release and is still being worked on please be patient :D

**Comment by mcagabe19** [comment]
chart editor is fixed and will include at beta 2 or stable release
