### ISSUE TITLE
can't open noteSplash debug editor

### ISSUE THREAD

**Issue by PHG29** [mcagabe19/FNF-PsychEngine-Mobile#10]
### Describe your bug here.

Well, when I try to open it, I just receive this screen error:

### Crash Log or logcat logs (if existing)

```bash
Null Object Reference
states/editors/NoteSplashDebugState.hx (line 289)
states/editors/NoteSplashDebugState.hx (line 134)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Karim-Akra** [comment]
Huh what that's odd T works fine or all of us
Try using the latest build

https://github.com/mcagabe19/FNF-PsychEngine-Mobile/releases/tag/0.7.1h-android

**Comment by Akhia11** [comment]
Outdated build bruh
