### ISSUE TITLE
Character editor error

### ISSUE THREAD

**Issue by Kivers69** [mcagabe19/FNF-PsychEngine-Mobile#12]
### Describe your bug here.

Idk why this happen

### Crash Log or logcat logs (if existing)

```bash
Null Object Reference
flixel/addons/ui/FlxUIDropDownMenu.hx (line 341)
states/editors/CharacterEditorState.hx (line 1067)
states/editors/CharacterEditorState.hx (line 437)
states/editors/CharacterEditorState.hx (line 191)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Karim-Akra** [comment]
Can you send a video for when it happens?

**Comment by Kivers69** [comment]
> Can you send a video for when it happens?


https://github.com/mcagabe19/FNF-PsychEngine-Mobile/assets/123798197/ce7a7d11-b13f-41c8-9ae8-2c25439cfa31

**Comment by mcagabe19** [comment]
> > Can you send a video for when it happens?
> 
>  Screenrecording_20230812_164121.mp4

did you tried latest actions build?

**Comment by Kivers69** [comment]
> > > Can you send a video for when it happens?
> > 
> > 
> > Screenrecording_20230812_164121.mp4
> 
> did you tried latest actions build? beacuse drop down is fine to me

No

**Comment by mcagabe19** [comment]
> > > > Can you send a video for when it happens?
> > > 
> > > 
> > > Screenrecording_20230812_164121.mp4
> > 
> > 
> > did you tried latest actions build? beacuse drop down is fine to me
> 
> No

try this
https://github.com/mcagabe19/FNF-PsychEngine-Mobile/suites/15032320984/artifacts/858384674

**Comment by Kivers69** [comment]
> > > > > Can you send a video for when it happens?
> > > > 
> > > > 
> > > > Screenrecording_20230812_164121.mp4
> > > 
> > > 
> > > did you tried latest actions build? beacuse drop down is fine to me
> > 
> > 
> > No
> 
> try this https://github.com/mcagabe19/FNF-PsychEngine-Mobile/suites/15032320984/artifacts/858384674

Still 
![Screenshot_20230812_175330](https://github.com/mcagabe19/FNF-PsychEngine-Mobile/assets/123798197/e45595f2-2440-419e-b042-423552af133c)

**Comment by MemeHovy** [comment]
try using a672653

**Comment by mcagabe19** [comment]
> try using [a672653](https://github.com/mcagabe19/FNF-PsychEngine-Mobile/commit/a6726538c0d9aa77a8f58509ddd1cb3ca86afbe3)

yea god damn drop down thing

**Comment by mcagabe19** [comment]
use that instead (hopefully) https://github.com/mcagabe19/FNF-PsychEngine-Mobile/actions/runs/5841884453
