### ISSUE TITLE
Sscript .hx files issue

### ISSUE THREAD

**Issue by PHG29** [mcagabe19/FNF-PsychEngine-Mobile#7]
### Describe your bug here.

When you load a Sscript a small issue happens, it does not crash the game but it's a little bit annoying...

### Crash Log or logcat logs (if existing)

```bash
[lime.utils.Assets] ERROR: There is no TEXT asset with an ID of "/storage/emulated/0/.PsychEngine/mods/scripts/script.hx"
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

Yeah, I just edited the path from data/com.shadowmario to .PsychEngine

**Comment by mcagabe19** [comment]
Read releases before making issue and also we can't fix that right now maybe after updates we can fix

![Screenshot_20230807_004141_Chrome](https://github.com/mcagabe19/FNF-PsychEngine-Mobile/assets/82843871/785c3e92-d291-4f96-8d0f-8ecf37d0ab03)

**Comment by PHG29** [comment]
uhh I was just asking if it was possible to remove it, but ok, ty
