### ISSUE TITLE
Lag Spikes through the game

### ISSUE THREAD

**Issue by PHG29** [mcagabe19/FNF-PsychEngine-Mobile#8]
### Describe your bug here.

It have some lag spikes when:

-Opening Substates (Pause menu,
CustomPauseSubstates, Gameover and etc)
-Messing with options (on main menu and mainly when you are in Playstate during a song)
-Changing note colors on the noteColor menu (somehow when using mouse on the color thing it goes to 20 fps lol)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing that could affect the lag directly, just paths

**Comment by mcagabe19** [comment]
ShadowMario killed performance _again_ and what build you downloaded?

**Comment by PHG29** [comment]
Well I made a fork with the lastest pull request of yours

**Comment by mcagabe19** [comment]
we don't know if we can fix so I have to close this issue
