### ISSUE TITLE
noteColorsMenu missing reset button

### ISSUE THREAD

**Issue by PHG29** [mcagabe19/FNF-PsychEngine-Mobile#9]
### Describe your bug here.

You can't actually reset the colors to default, bc there's no button for it (ik it's crashing but what are you using? Maybe you forgot something or idk)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Karim-Akra** [comment]
The last build in actions added it

**Comment by PHG29** [comment]
Thanks
